### ISSUE TITLE
Add "meaning" column to cognatesets table

### ISSUE THREAD

**Issue by xrotwang** [clld/cobl2#2]
http://cobl.clld.org/cognatesets should have a column "meaning", in particular to distinguish cognate sets with same root form.

**Comment by Bibiko** [comment]
Adding "Meaning" to the table is trivial, but what is the clld philosophy to make it sortable and searchable since the data doesn't live in the CognateClass model? The normal workflow is clear, subclassing LinkCol and adding the methods `order` and `search` - but how?

**Comment by xrotwang** [comment]
You have to override base_query of the DataTable, joining wherever Meaning
is available.

Hans-Jörg Bibiko <notifications@github.com> schrieb am So., 17. März 2019,
12:07:

**Comment by xrotwang** [comment]
There should be many examples for this technique in basically any clld app.

Robert Forkel <xrotwang@googlemail.com> schrieb am So., 17. März 2019,
12:24:
